version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:8-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        links:
            - mariadb
        depends_on:
            - mariadb
        build:
            context: .
            dockerfile: Dockerfile

    mariadb:
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: estacioneaqui
        MYSQL_USER: pedro
        MYSQL_PASSWORD: 1234
      volumes:
       - /var/lib/mysql
      ports:
        - "3306:3306"
    composer:
      image: composer:2
      volumes:
        - ./:/var/www/html
      working_dir: /var/www/html
      command: ["update", "--ignore-platform-reqs"]
